#!/bin/bash
#this script automaticly locates all git repositories on the local pc and updates them
txtgrn='\e[0;32m\033[1m ' # Green bold
txtora='\e[0;31m\033[1m ' # Orange bold
txtrst='\e[0m'            # Text Reset
list=0;
    case "$1" in
        -h|--help )
            echo "options:"
            echo "-h, --help  show brief help"
            echo "-l          for listing directories"
            shift 2
            exit
        ;;
        -l )
            list=1
            shift 2
        ;;
    esac 

if [ -n "`which locate`" ];then
	echo "========================BEGIN CHECK==============================="
	IGNORE="/usr/local|/var/www";#insert dirs to ignore, like this DIR1|DIR2|DIR3
	GETDIRS=`locate ".git/index" | grep -vE "$IGNORE"` #get all dirs on the local pc with a git repository

	#counters
	COMMITTED=0
	NOTCOMMITTED=0
	ALL=0

	for i in $(echo "$GETDIRS" )
	do
		 temp=${i/.git\/index/} 
		 if [ $list == 1 ];then
			echo "$temp"
		 fi
		 cd "$temp"
		 empty=`git status -s`
		if [ -n "$empty" ]; then
		 echo -e "!!! $temp => not committed files "
		 let NOTCOMMITTED++
		 #not committed files in this repository, do what you want here
		else
		 let COMMITTED++
		 #all files in this repository are committed, do what you want here
		fi
		let ALL++
	done

	if [ $NOTCOMMITTED == 0 ];then
		end="$txtgrn✔$txtrst"
	else
		end="$txtora✘$txtrst"
	fi
	echo "------------------------------------------------------------------"
	echo -e "\t $ALL dirs total, committed $COMMITTED, not committed $NOTCOMMITTED $end"
	echo "========================CHECK DONE================================"
else
	echo -e "$txtora Please install locate. \n$txtrst"
fi
